/*
 * 			AlarmEnable Testbench
 -----------------------------------
 
 This is a Testbench for AlarmEnable module
 which verifies the working of Alarm.
 -----------------------------------
 *  	Created on: 5 May 2023
 *      Author: Lohitha Lakshmi Guggilam
 */

`timescale 1 ns/100 ps

 module AlarmEnable_tb;
 
	reg clk;

	//Signals for input generated by test bench
	reg [5:0] alarm_hour;
	reg [5:0] alarm_min;
	reg switch_enable;
	reg [5:0] current_hour;
	reg [5:0] current_min;

	// DUT Output Signal  
	wire alarm_enable_LED;
	wire alarm_LED;

	// Device Under Test Instantiation
	AlarmEnable AlarmEnable_dut(
		.clk(clk),
		.alarm_hour(alarm_hour),
		.alarm_min(alarm_min),
		.switch_enable(switch_enable),
		.current_hour(current_hour),
		.current_min(current_min),
		.alarm_enable_LED(alarm_enable_LED),
		.alarm_LED(alarm_LED)
	  );

	//Clock Initialization
	initial begin
		clk = 0;
		forever #1 clk=~clk;	  
	end
	
	initial begin
	
		//Giving test Time values to Alarm time and Current time
		alarm_hour = 1;
		alarm_min = 15;	
		current_hour = 1;
		current_min = 15;	
	end
	
	//Testbench logic
	always @(*) begin
	
		//Alarm Enabled
		switch_enable = 0;
		#10
		switch_enable = 1;
		#10;
		
		//Verify alarm is triggered
		if(alarm_LED == 1) begin
			$display("Sucesssful Alarm");
		end
		else begin
			$display("Error!! Alarm not triggered as expected");
			$stop;
		end
		
		assign current_min = current_min + 2;
		#10;
		
		// Verify alarm is turned off after 2 minutes
		if(alarm_LED == 0) begin
			$display("Alarm End");
		end
		else begin
			$display("Error!! Alarm not turned off after 2 min");
			$stop;
		end
	
	end

 endmodule  
  